### ISSUE TITLE
peter老师，请问有一次在好多视频网评论中有位同学提到你的录视频风格，说很像某某，忘了那是谁。

### ISSUE THREAD

**Issue by venicehsu** [happypeter/ask#10]
之前在好多视频网评论区看到的，你说你很喜欢那位老师，你的讲课风格受他的影响很大，如今他自己做了个视频网站，自己录的课放在上面。
1.那位外国老师叫什么名字？
2.他自立门户之前的视频是发布在哪个网站上的？
3.他自己创立的网站叫什么名字？

**Comment by happypeter** [comment]
是 jeffery way ，目前他在 laracasts.com ，以前他是 tutsplus 的讲师
