### ISSUE TITLE
HTTP 下午茶 图片挂了。

### ISSUE THREAD

**Issue by byr-gdp** [happypeter/ask#12]
https://www.gitbook.com/book/ccbikai/http-book/details

很不错的教程，花了一小时通读了一遍，对个别细节的理解更进了一步，不过图片在我这都挂了... 

:)

**Comment by happypeter** [comment]
这本书要大改版了，而且名字也会改成 《learn Http With Peter》，所以请关注我的朋友圈更新。

我微信：happypeter1983
