### ISSUE TITLE
您从事IT有多少年了？视频还有网站都是工作之余录制和编写的吗？你是如何平衡两者的？O(∩_∩)O谢谢！

### ISSUE THREAD

**Issue by chairmanview** [happypeter/ask#14]

**Comment by happypeter** [comment]
十年了。我是录制视频之余去接一些项目做的，视频是主业。

**Comment by oqq5518** [comment]
你一般是哪里接的项目阿？我也想成为一个自由职业 哈哈

**Comment by happypeter** [comment]
钱来自三个途径：
- 秦皇岛这边我会线下讲 JS
- 《摩登前端开发者》线上课
- 项目都是朋友圈子介绍的，我没有固定接项目的方式

**Comment by oqq5518** [comment]
录完的时候要剪辑吗？如果要的话，是直接用screenflow处理吗？

**Comment by happypeter** [comment]
对，至少要剪几十下，都是在 screenflow 里处理的。

**Comment by oqq5518** [comment]
react-transform-boilerplate的作者已经停止维护了，webpack的脚手架还有其他推荐的吗

**Comment by happypeter** [comment]
https://github.com/facebookincubator/create-react-app

**Comment by oqq5518** [comment]
我一点atom的open-in-browser，它就自动打开我的虚拟机，然后用里面的程序打开当前源文件。你知道怎么设置吗？
