### ISSUE TITLE
React in Meteor中，用户问题。

### ISSUE THREAD

**Issue by Here21** [happypeter/ask#2]
还是没太明白，就是在Meteor中结合React，发布与订阅怎么实现？用户注册应该怎么自己去订制？主要是API的哪些接口不懂，没什么思路。
关于用户注册的API是Password部分么？而Accounts部分的API是对用户行为进行操作的？
不同的路由是否可以共同使用？

**Comment by happypeter** [comment]
这些都是非常重要的问题，全栈开发中肯定会涉及到的。

《摩登》课程第三个阶段中，对这些问题会详细讲解的。
