### ISSUE TITLE
在rails项目中，前端开发要怎么进行

### ISSUE THREAD

**Issue by chenbin92** [happypeter/ask#3]
Hi peter：

问题：作为一名不懂rails的前端，需要如何在rails项目中进行前端开发？

困惑一：rails 的 asset pipeline 已经很好的处理了 CSS、JavaScript 静态资源的压缩问题，Sass、CoffeeScript 的编译问题等等，提供了一整套的解决方案；那相对于来说：前端的自动化构建工具，比如gulp，webpack 等在 rails 项目里失去了用武之地；举个例子：比如我需要使用 autoprefixer, 如果是前后端分离，那我可以在 gulp 里配置 autoprefixer；而在 rails 里虽然也有 autoprefixer-rails gem, 但不是所有的插件都有人去封装对应的 rails gem；这对前端来说不够友好。

困惑二： 在 rails 项目中，前后端先按照PSD 转成HTML，添加交互；然后给后端去集成，也就是套页面的过程，之后还会有一些兼容性的问题，需要前端再反过去调整，这个过程是会反复交叉持续的；难免在这个过程会出现问题，另外，前端也需要去学习基本的的 rails 概念，也会增加新人的学习成本 。

**Comment by happypeter** [comment]
首先 asset pipeline 是自身是饱受诟病的，我个人对它的评价是：极其复杂，但不强大。但是另外，前端确实再以“每18个月复杂一倍”的速度在发展，这样前后分离又应该是趋势的，所以即使 asset pipeline 设计是良好的，也基本是一个错误的方向。（ Rails 社区把 rails-api 合并到 Rails5 中，相信也是意识到了这一点）

目前除了做 SPA ，全栈方面我已经放弃 Rails 改用 meteor ，meteor 前后分离得是非常好的，也可以用 npm/browserify/react 整个那一套。

**Comment by happypeter** [comment]
关于困惑二：

我个人的感觉是： Rails 真得不是给多人团队设计的，（DHH 其实早期一直是一个人在战斗），所以，我赞同你的感受。但是，我想说的是，即使是用 SPA 前后分离的架构，当代优秀的前端也应该是不同以往的（也还是要懂得 js module/npm/commandline/router ），所以

> 优秀的前端应该就应该是全栈

这个是我的建议。只是我现在已经不推荐 rails 了。用 nodejs ，前后都吃得开。
