### ISSUE TITLE
webapck 打包文件太大如何解决？

### ISSUE THREAD

**Issue by AnnatarHe** [happypeter/ask#4]
Peter老师你好。

我来试试这个ask效果如何~哈哈~

我最近用webpack + react做了一个简历页面。

源码在这里：[AnnatarHe/iamhele.com](https://github.com/AnnatarHe/iamhele.com)

然而打包出来的文件足足有1.9M大。

浏览页面，14s才把js文件下载完。

[这里预览](http://iamhele.com)

所以请问一下老师有没有什么合适的方法能缩小一点儿文件大小。

最好是拆分成3-4的请求的样子。

谢谢老师 ^_^

**Comment by happypeter** [comment]
webpack 的一大优势就是有，分割和异步加载打包后的文件的功能。这个 Peter Hunt 在 youtube 的一个视频中专门提过的，webpack 官方文档中也有。

不过我还没有试过。您那边有进展了欢迎分享啊，谢谢！

**Comment by forecho** [comment]
可以看一下这个 [Demo10: Code splitting](https://github.com/ruanyf/webpack-demos/blob/master/README.md#demo10-code-splitting-source)

**Comment by AnnatarHe** [comment]
好的，谢谢啦。过会儿去试试

**Comment by happypeter** [comment]
公开讨论问题就是有好处，大家都可以进来帮忙的，yeah

**Comment by AnnatarHe** [comment]
忘记回复了。
要配置插件来着

``` js
plugins: [
        new webpack.optimize.UglifyJsPlugin({
            compress: {
                warnings: false
            }
        })
    ]
```

这样就压缩成了220kb

然后gzip压缩下。这样就只有60kb左右。

关于分片之前看过一点儿，没怎么搞懂。感觉60kb暂时还可以接受。

**Comment by happypeter** [comment]
@AnnatarHe 这个真好，我回头要用起来。

**Comment by happypeter** [comment]
https://github.com/gaearon/react-transform-boilerplate/blob/master/webpack.config.prod.js

也推荐了这个方法。

**Comment by zhenhappy** [comment]
我觉得压缩代码只是一个解决办法，但是有更好的解决办法，就是利用localstorage把js和css等资源保存起来，下次访问直接读取, 具体可以看这个家伙的网站 https://imququ.com ,这是我见过加载速度最快的网站了，大家可以看下

**Comment by happypeter** [comment]
@zhenhappy 真是超级快，localstorage 缓存起来当然是可以加快第二次的页面打开速度。

但是，首次打开网站的速度应该就帮不上忙了吧？

**Comment by zhenhappy** [comment]
@happypeter 首次加载的话可以采用CDN加速js,css等资源文件的解决方案，经过这样几下子优化，我觉得效果已经很不错了

**Comment by happypeter** [comment]
@zhenhappy 嗯嗯，这个的确是好方法
