### ISSUE TITLE
路由相关问题

### ISSUE THREAD

**Issue by Here21** [happypeter/ask#5]
iron:router中：

```
Router.go('home');
```

这是重定向的意思吗？
在react router中，我看到也有`go`的API，是否功能一样？

**Comment by happypeter** [comment]
iron 没有用过。

**Comment by happypeter** [comment]
google 一下 “react-router go" 就可以找到官方文档。注意，会查手册跟会使用 google 一样，也是开发者的必备素质。

https://github.com/rackt/react-router/blob/master/docs/API.md#gon

**Comment by happypeter** [comment]
> go(n)
> 
> Go forward or backward in the history by n or -n.

这个是在浏览历史（ history ）中前进或者后退用的，不是重定向。

关于浏览器的 history 接口，《摩登》课程中会有介绍。
