### ISSUE TITLE
About the meteorjs.(New meteorjs study)

### ISSUE THREAD

**Issue by thinksource** [happypeter/ask#6]
I am just look at the meteor.js, wonder fellows:

1, it seems currently the meteorjs only focus on mongodb, but for those relationship which is not easy to represent in mongodb like many to many relationships how to deal with those orm?

2, How do you did data migration, do meteorjs provide some tools for that?

3, what kind of technology meteorjs deal with package management, can I apply other package like ojbect.js replace the meteor by myself?

4, what kind of technology meteorjs used replace the REST.

**Comment by happypeter** [comment]
> 1, it seems currently the meteorjs only focus on mongodb, but for those relationship which is not easy to represent in mongodb like many to many relationships how to deal with those orm?

As far as I know , Meteor team is working on support for some sql things.

**Comment by happypeter** [comment]
> 2, How do you did data migration, do meteorjs provide some tools for that?

It's also a WIP i think. try google this.

**Comment by happypeter** [comment]
> 3, what kind of technology meteorjs deal with package management, can I apply other package like ojbect.js replace the meteor by myself?

meteorjs package management system is a first class citizen. Two things: NO.1 https://atmospherejs.com/ NO.2 npm

In the demo of my online training: qd.haoduoshipin.com

I used both for one project. worked like a charm!

**Comment by happypeter** [comment]
> 4, what kind of technology meteorjs used replace the REST.

It's a whole new era now. People expect their app work real time, and meteorjs took the approach of "Real Time By Default" . So it's now data publish/subscription to user server data. It's 100% different form the traditional REST REQUEST module. I think this is cool.

Sure, you can still send REST things for some API data through ajax or something. But in some way, REST is the way of past.
