### ISSUE TITLE
I try to use the meteor-postgres, but fail do you know how to use the meteor-postgres

### ISSUE THREAD

**Issue by thinksource** [happypeter/ask#7]
The issue is [here](https://github.com/storeness/meteor-postgres/issues/7).
I already reported.
Do you know how to use the meteor with postgres?

I want to develop common e-shop via meteor.js. But I do not want to apply it on mongodb as it schema-less and I find the lost to inner join selection(cross table search ) after you build the e-shop.
Any suggest about the database designing if I want to build:

 1,Consistency.
 2, Visibility of data and the behaviour of the system.
 3,Correctness and explicitness.
 4,Scalability.

**Comment by happypeter** [comment]
Never used postgres before. Sorry
