### ISSUE TITLE
peter老师，请问在小白变怪兽的网页中，是如何做到左边的播放按钮与右边的详情等高的？

### ISSUE THREAD

**Issue by WuHuaJi0** [happypeter/ask#9]
http://c.haoduoshipin.com/guaishou/index.html

我当前在临摹这个页面，我搜索了网上的两列等高布局，通常是用“padding补偿法”，但是我尝试这种方法，会导致背景图片中的播放图标跑出了中心位置。

我尝试查看您是怎么写的。发现您在a.video里写的是：

``` css
a.video{
    height: 100%;
}
```

但是我想到，这里height:100%起作用的前提是，父元素有高度，但是在父元素div class=card这个容器中，并没有看到相关的高度设置，那card的高度显然是被子元素撑搞的。

所以想请问您是如何做到的？

**Comment by happypeter** [comment]
```
.card a.video {
    display: block;
    height: 100%;
    width: 60px;
    position: absolute;
    /* top: 0; */
    /* left: 0; */
    background: #41a9cc url("images/play_list_big.png") no-repeat 22px 50%;
}
```

上面的  `position: absolute;` 起了关键作用。没有它，确实 `height: 100%` 是不灵的。

**Comment by WuHuaJi0** [comment]
实验出来了，谢谢peter老师 : D
